require 'luavg'

local width, height = 640, 400
local colors = {
    ink = "#263238",
    paper = "#fffdf7",
    coral = "#e76f51",
    gold = "#e9c46a",
    teal = "#2a9d8f",
    blue = "#457b9d",
}

local illustration = SVG({
    width = width,
    height = height,
    viewBox = ("0 0 %d %d"):format(width, height),

    Title({ "LuaVG SVG element showcase" }),
    Desc({ "A single drawing composed with LuaVG shape, text, and resource helpers." }),
    Metadata({ "Generated by samples/showcase/showcase.lua" }),

    Defs({
        LinearGradient({
            id = "sunset",
            x1 = "0%",
            y1 = "0%",
            x2 = "100%",
            y2 = "100%",
            Stop({ offset = "0%", stop_color = colors.gold }),
            Stop({ offset = "100%", stop_color = colors.coral }),
        }),
        RadialGradient({
            id = "halo",
            cx = "50%",
            cy = "50%",
            r = "50%",
            Stop({ offset = "0%", stop_color = colors.gold, stop_opacity = "0.8" }),
            Stop({ offset = "100%", stop_color = colors.gold, stop_opacity = "0" }),
        }),
        Pattern({
            id = "dots",
            width = 14,
            height = 14,
            patternUnits = "userSpaceOnUse",
            Circle({ cx = 3, cy = 3, r = 1.5, fill = colors.teal }),
        }),
        ClipPath({
            id = "plot-clip",
            Rect({ x = 48, y = 104, width = 340, height = 170, rx = 18 }),
        }),
        Mask({
            id = "label-mask",
            Rect({ x = 0, y = 0, width = 240, height = 48, fill = "white" }),
            Circle({ cx = 218, cy = 24, r = 15, fill = "black" }),
        }),
        Marker({
            id = "arrow",
            markerWidth = 8,
            markerHeight = 8,
            refX = 7,
            refY = 4,
            orient = "auto",
            markerUnits = "strokeWidth",
            Path({ d = "M 0 0 L 8 4 L 0 8 z", fill = colors.blue }),
        }),
        Symbol({
            id = "spark",
            viewBox = "0 0 40 40",
            Path({
                d = "M20 0 L25 14 L40 20 L25 26 L20 40 L15 26 L0 20 L15 14 Z",
                fill = colors.coral,
            }),
        }),
    }),

    Rect({ x = 0, y = 0, width = width, height = height, fill = colors.paper }),
    Rect({ x = 22, y = 22, width = 596, height = 356, rx = 24, fill = "url(#dots)" }),
    Rect({ x = 30, y = 30, width = 580, height = 340, rx = 20, fill = colors.paper }),

    Text({ x = 52, y = 76, fill = colors.ink, font_size = 25, font_family = "sans-serif", font_weight = "700" }, "A small SVG field guide"),
    Text({
        x = 54,
        y = 96,
        fill = colors.blue,
        font_size = 12,
        font_family = "sans-serif",
        [1] = TSpan({ font_weight = "700" }, "shapes"),
        [2] = TSpan({ dx = 5 }, "+ paths + reusable resources"),
    }),

    Group({
        id = "plot",
        clip_path = "url(#plot-clip)",
        Rect({ x = 48, y = 104, width = 340, height = 170, rx = 18, fill = "url(#sunset)" }),
        Ellipse({ cx = 214, cy = 190, rx = 115, ry = 74, fill = "url(#halo)" }),
        Polygon({
            points = {
                { x = 54, y = 250 },
                { x = 142, y = 160 },
                { x = 218, y = 232 },
                { x = 282, y = 174 },
                { x = 384, y = 260 },
            },
            fill = colors.teal,
            fill_opacity = "0.9",
        }),
        Polyline({
            points = {
                { x = 72, y = 223 },
                { x = 144, y = 185 },
                { x = 212, y = 204 },
                { x = 294, y = 145 },
                { x = 360, y = 164 },
            },
            fill = "none",
            stroke = colors.ink,
            stroke_width = 3,
            stroke_linecap = "round",
            stroke_linejoin = "round",
        }),
        Path({
            d = "M 74 244 C 126 224 148 254 196 238 S 284 214 352 236",
            fill = "none",
            stroke = colors.paper,
            stroke_width = 3,
            stroke_dasharray = "6 7",
        }),
        Circle({ cx = 294, cy = 145, r = 7, fill = colors.paper, stroke = colors.ink, stroke_width = 2 }),
    }),

    Line({
        x1 = 405,
        y1 = 124,
        x2 = 565,
        y2 = 124,
        stroke = colors.blue,
        stroke_width = 2,
        marker_end = "url(#arrow)",
    }),
    Use({ href = "#spark", x = 424, y = 145, width = 40, height = 40 }),
    Use({ href = "#spark", x = 476, y = 154, width = 24, height = 24, opacity = "0.65" }),

    Group({
        transform = "translate(408 210)",
        Rect({ x = 0, y = 0, width = 164, height = 54, rx = 12, fill = "url(#sunset)" }),
        Text({ x = 16, y = 34, fill = colors.ink, font_size = 18, font_family = "sans-serif", mask = "url(#label-mask)" }, "Reusable paint"),
    }),

    Image({
        x = 526,
        y = 278,
        width = 56,
        height = 40,
        preserveAspectRatio = "none",
        href = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='64' height='40'%3E%3Crect width='64' height='40' rx='8' fill='%23e9c46a'/%3E%3Ccircle cx='32' cy='20' r='8' fill='%23e76f51'/%3E%3C/svg%3E",
    }),
    Anchor({
        href = "#plot",
        Text({ x = 408, y = 302, fill = colors.blue, font_size = 13, font_family = "sans-serif", text_decoration = "underline" }, "Link to the plot"),
    }),
    ForeignObject({
        x = 52,
        y = 300,
        width = 290,
        height = 42,
        SVGElement("div", {
            xmlns = "http://www.w3.org/1999/xhtml",
            style = "font: 13px sans-serif; color: #263238; padding: 8px 10px; background: #e9c46a; border-radius: 8px;",
            "HTML inside ForeignObject",
        }),
    }),
}):save("samples/showcase/showcase.svg")
